version: '2'
services:
    new_local-app:
        image: new_local
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://new_local-postgresql:5432/New_Local
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://new_local-elasticsearch:9200
        ports:
            - 8080:8080
    new_local-postgresql:
        extends:
            file: postgresql.yml
            service: new_local-postgresql
    new_local-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: new_local-elasticsearch
